In [66]:
import pandas as pd
from datetime import datetime

In [68]:
bfp_prod_path = 'C:/Users/jbeachy/Moss & Associates/Data Management - Data Team/Projects/BFP Weather/BFP Plan of Day Master.xlsx'
bfp_df_raw = pd.read_excel(bfp_prod_path , sheet_name = 'Mech')

In [94]:
col_name = bfp_df_raw.iloc[0,0:18].fillna('Date')
bfp_df_full = bfp_df_raw.iloc[4:,0:18].rename(columns = col_name).reset_index(drop = True)
bfp_df_full['Date'] = pd.to_datetime(bfp_df_full['Date'])
bfp_df_full['dayofweek'] = bfp_df_full.loc[:,'Date'].dt.strftime('%a')

In [97]:
bfp_df_full.head()

,Date,Piles (Ea),Brackets,NS Beams (Ea),Beam Cover,Purlins (Ea),Racking (Mod),CAB Post (Ea),465W,460W (Ea),380W (Ea),Modules,Pile Refusals,Broken 465W,Broken 460W,Broken 380W,Warranty 460W,Warranty 380W,dayofweek
0,2022-06-20,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mon
1,2022-06-21,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tue
2,2022-06-22,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wed
3,2022-06-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Thu
4,2022-06-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fri

In [102]:
bfp_piles = bfp_df_full.loc[:,['Date','dayofweek','Piles (Ea)']]

In [103]:
bfp_piles

          Date dayofweek Piles (Ea)
0   2022-06-20       Mon        NaN
1   2022-06-21       Tue        NaN
2   2022-06-22       Wed        NaN
3   2022-06-23       Thu        NaN
4   2022-06-24       Fri        NaN
..         ...       ...        ...
190 2022-12-27       Tue          0
191 2022-12-28       Wed          0
192 2022-12-29       Thu          0
193 2022-12-30       Fri          0
194 2022-12-31       Sat          0

[195 rows x 3 columns]